name: marriage_onchain_web
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
    

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3

  # State Management
  provider: ^6.1.2

  # Web3
  flutter_web3: ^2.1.9
  go_router: ^14.8.1
  simple_animations: ^5.1.0
  web3dart: ^2.7.3
  http: ^1.3.0
  ens_dart:
    path: /Users/immadominion/codes/opensauce/ens_dart
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Variable.ttf